# FastAgent Configuration File

# Default Model Configuration:
#
# Takes format:
#   <provider>.<model_string>.<reasoning_effort?> (e.g. anthropic.claude-3-5-sonnet-20241022 or openai.o3-mini.low)
# Accepts aliases for Anthropic Models: haiku, haiku3, sonnet, sonnet35, opus, opus3
# and OpenAI Models: gpt-4.1, gpt-4.1-mini, o1, o1-mini, o3-mini
#
# If not specified, defaults to "haiku".
# Can be overriden with a command line switch --model=<model>, or within the Agent constructor.
generic:
  # base_url: "http://localhost:11434/v1"
  base_url: "https://56f6-34-125-42-179.ngrok-free.app/v1"
# default_model: "generic.llama3.1:8b"

google:
  base_url: "https://generativelanguage.googleapis.com/v1beta/openai"
default_model: "google.gemini-2.0-flash"

anthropic:
  base_url: "https://api.anthropic.com/v1"
#default_model: "haiku"
openai:
  base_url: "https://openrouter.ai/api/v1"
# default_model: "openai.nvidia/llama-3.1-nemotron-ultra-253b-v1:free"

# Logging and Console Configuration:
logger:
#  level: "debug"
#  type: "console"

  # Switch the progress display on or off
  progress_display: true

  # Show chat User/Assistant messages on the console
  show_chat: true
  # Show tool calls on the console
  show_tools: true
  # Truncate long tool responses on the console
  truncate_tools: true

# MCP Servers
mcp:
  servers:
    playwright:
      command: "npx"
      args: [
        "@playwright/mcp@latest",
        "--isolated"
      ]
    playwright_e: {
      command : "npx",
      args: [ "-y", "/Users/usama.jalal/playwright_mcp/mcp-playwright/dist/index.js" ]
    }
    filesystem:
      command: "npx"
      args:
        [
          "-y",
          "@modelcontextprotocol/server-filesystem",
          "${MANUAL_TEST_CASE_FOLDER_PATH}",
          "${PLAYWRIGHT_PROJECT_PATH}",
        ]
